import { existsSync, renameSync } from 'node:fs';
import { defineConfig } from 'tsdown';

// Two artifacts, TWO builds — never one code-splitting build:
//
//   client.js          the plugin (code)
//   client.artwork.js  the built-in frames (data, generated by
//                      tools/gen-artwork.py), fetched on demand through the
//                      module loader's require.async('./client.artwork.js')
//
// The client module loader fetches each with a plain <script> tag (a classic
// script, no ESM), so each output must be a self-contained IIFE that
// registers itself via window.__ModuleLoader__.load().  IIFE and code
// splitting cannot be combined, hence one config per artifact.

const shared = {
  format: 'iife' as const,
  outDir: '.',
  clean: false, // outDir is the package root — never clean it
  dts: false, // private bundle, no type consumers
  minify: false,
  sourcemap: false,
  target: 'es2019',
  hooks: {
    // tsdown hardcodes a `.iife` filename suffix; the loader contract expects
    // the artifacts at exactly ./client.js and ./client.artwork.js.
    'build:done': () => {
      for (const name of ['client', 'client.artwork']) {
        if (existsSync(name + '.iife.js')) renameSync(name + '.iife.js', name + '.js');
      }
    },
  },
};

export default defineConfig([
  { ...shared, name: 'client', entry: { client: 'src/main.ts' } },
  { ...shared, name: 'artwork', entry: { 'client.artwork': 'src/artwork-chunk.ts' } },
]);
