// Labels — every visible string, in every shipped locale.  Keys are state
// and reaction names (plus `toolNamed`, the tool state's `{name}` variant),
// so the dictionaries and the registries cannot drift — the test suite
// asserts both locales carry identical key sets and cover every registry
// entry.

export const NS = 'status-pet';

export type LabelDict = Record<string, string>;

export const LABELS: Record<'en' | 'zh', LabelDict> = {
  en: {
    label: 'Status Pet',
    idle: 'Idle', sleep: 'Sleeping', think: 'Thinking…', stream: 'Responding…',
    tool: 'Running a tool…', toolNamed: 'Running {name}…',
    approval: 'Waiting for your approval',
    question: 'Waiting for your answer', error: 'Something went wrong',
    done: 'Done', petted: 'Blushing', woken: 'Woken up',
    'settings.nav': 'Status Pet',
    'settings.previewHint': 'Click to pet it',
    'settings.tab.preview': 'Preview',
    'settings.tab.edit': 'Edit',
    'settings.skins': 'Skin',
    'settings.skin.whale-chan': 'Whale-chan',
    'settings.skin.cat': 'Classic Cat',
    'settings.skin.custom': 'My Creation',
    'settings.grid.32': 'Avatar (32×32)',
    'settings.grid.128': 'Full body (128×128)',
    'settings.brushN': 'Brush {n}',
    'settings.eraser': 'Eraser',
    // ── the gallery ──
    'settings.view': 'Preview mode',
    'settings.view.states': 'By state',
    'settings.view.actions': 'By action',
    'settings.unusedCount': '{n} action(s) no state plays yet',
    'settings.showMore': 'Show more',
    'settings.actionFrames': '{n} frames',
    // ── the studio's field spine ──
    'settings.region.states': 'States',
    'settings.region.action': 'Action',
    'settings.region.canvas': 'Canvas',
    'settings.region.frames': 'Frames (played in order)',
    'settings.region.palette': 'Brushes',
    'settings.region.library': 'Actions',
    'settings.region.preview': 'Preview',
    'settings.region.frame': 'Current frame',
    'settings.field.frames': 'Frames',
    // ── the action library ──
    'settings.libraryHint': 'Every animation this crop owns. Ticking one means the selected state plays it. One action can be ticked in several states — editing it once changes all of them. Deleting actions lives in By action · Batch delete.',
    'settings.actionHint': 'The one action the board edits. Which states play it is ticked in By state.',
    'settings.assignCropMissing': 'This crop has no artwork yet — generate it in Edit · By action.',
    'settings.builtinStatesOnly': 'A built-in\'s artwork is fixed. What you CAN change here is which of its actions each state plays — draw your own in My Creation.',
    'settings.clearIdleHint': 'Idle must keep at least one action: every state with nothing ticked falls back to it. None therefore keeps the FIRST one instead of leaving Idle empty.',
    'settings.editAction': 'Edit this action',
    'settings.editState': 'Choose what this state plays',
    'settings.actionCount': '{n} action(s)',
    'settings.actionN': 'Action {n}',
    'settings.actionName': 'Name',
    'settings.actionNameHint': 'Optional label, shown in this list only.',
    'settings.newAction': 'New action',
    'settings.deleteAction': 'Delete action',
    'settings.deleteUsed': 'Delete this action — {n} state(s) play it',
    'settings.importAction': 'Import action',
    'settings.importSearch': 'Search actions…',
    'settings.importHint': 'Pick one: it replaces the action you are editing — name, frames and pace. The states that play it keep playing it, and Undo brings your drawing back.',
    'settings.importSource.builtin': 'Built-in',
    'settings.importSource.mine': 'Mine',
    'settings.importCurrent': 'current',
    'settings.importedOne': 'Imported {name}',
    'settings.usedByN': '{n} state(s) play this',
    'settings.unusedAction': 'no state plays this yet',
    'settings.playedHere': 'This state plays it',
    'settings.emptyLibrary': 'This crop has no actions yet.',
    // ── the assignment list is two groups: what this state ticks comes first ──
    'settings.libraryTickedGroup': 'Ticked for this state ({n})',
    'settings.libraryRestGroup': 'Other actions ({n})',
    'settings.libraryFull': 'The library is full.',
    'settings.selectAll': 'All',
    'settings.clearSelection': 'None',
    // ── finding and bulk-editing actions ──
    'settings.searchActions': 'Search actions…',
    'settings.searchStates': 'Search states…',
    'settings.searchMatches': '{n} of {total}',
    'settings.searchEmpty': 'No action matches “{q}”.',
    'settings.selectedCount': '{n} ticked',
    'settings.selectedMax': '{n} ticked (the limit)',
    'settings.manageActions': 'Batch delete',
    'settings.bulkHint': 'Tick the actions to remove, then Delete selected — a dialog confirms it, because a removal is not undoable.',
    'settings.selectAllHint': 'All ticks every action the search matches, not just the tiles on screen.',
    'settings.confirmDeleteTitle': 'Delete {n} action(s)?',
    'settings.confirmDeleteHint': 'They leave the library, and every state that plays them loses the reference. This cannot be undone.',
    'settings.cancel': 'Cancel',
    'settings.confirmDelete': 'Delete',
    'settings.deleteSelected': 'Delete selected',
    'settings.deleteBlocked': 'The crop must keep at least one action, and Idle must keep one it plays.',
    'settings.actionsRemoved': 'Removed {n} action(s)',
    'settings.followIdle': 'follows Idle',
    'settings.actionMs': 'Default per frame',
    'settings.actionMsHint': 'One pace per action: every state that plays it uses this number.',
    'settings.addFrame': 'Duplicate frame',
    'settings.addBlankFrame': 'Blank frame',
    'settings.emptyBody': 'No full-body artwork yet — the popup shows the avatar at 4×.',
    'settings.blankBody': 'Start from a blank grid',
    'settings.hint.idle': 'At rest, nothing running',
    'settings.hint.sleep': 'After a minute idle',
    'settings.hint.think': 'Message sent, no output yet',
    'settings.hint.stream': 'Output is arriving',
    'settings.hint.tool': 'A tool is executing',
    'settings.hint.approval': 'Waiting for your approval',
    'settings.hint.question': 'Waiting for your answer',
    'settings.hint.error': 'The last turn failed',
    'settings.hint.done': 'Finished, not yet seen',
    'settings.hint.petted': 'Right after a click',
    'settings.hint.woken': 'Hover or focus while asleep',
    'settings.export': 'Export',
    'settings.import': 'Import',
    'settings.io': 'Import / export JSON',
    'settings.importError': 'That is not a valid sprite',
    'settings.undo': 'Undo',
    'settings.redo': 'Redo',
    'settings.paste': 'Paste',
    'settings.genBody': 'Generate the 128×128 draft from the avatar',
    'settings.frameLen': 'This frame',
    'settings.frameOffset': 'Nudge frame',
    'settings.frameOffsetHint': 'Moves this whole frame without redrawing it — that is how a bob or a sway is made.',
    'settings.offsetReset': 'Reset',
    'settings.frameProp': 'Accent',
    'settings.framePropClear': 'Remove accent',
    'settings.framePropHint': 'An imported accent (sleep bubbles, an exclamation…) drawn over the body. It is not part of the board, so it can only be removed here.',
    'settings.moveUp': 'Move up', 'settings.moveDown': 'Move down',
    'settings.moveLeft': 'Move left', 'settings.moveRight': 'Move right',
    'settings.frameN': 'Frame {n}',
    'settings.framePrev': 'Move frame earlier', 'settings.frameNext': 'Move frame later',
    'settings.copyFrame': 'Copy to clipboard',
    'settings.delFrame': 'Delete frame',
    'settings.frameMs': 'ms/frame',
  },
  zh: {
    label: '状态宠物',
    idle: '空闲', sleep: '睡觉中', think: '思考中…', stream: '回复中…',
    tool: '正在执行工具…', toolNamed: '正在执行 {name}…',
    approval: '等待你批准',
    question: '等待你回答', error: '出错了',
    done: '已完成', petted: '害羞了', woken: '被叫醒了',
    'settings.nav': '状态宠物',
    'settings.previewHint': '点一下，摸摸它',
    'settings.tab.preview': '预览',
    'settings.tab.edit': '编辑',
    'settings.skins': '皮肤',
    'settings.skin.whale-chan': '鲸鱼娘',
    'settings.skin.cat': '经典橘猫',
    'settings.skin.custom': '我的创作',
    'settings.grid.32': '头像 (32×32)',
    'settings.grid.128': '全身 (128×128)',
    'settings.brushN': '画笔 {n}',
    'settings.eraser': '橡皮',
    // ── 预览 ──
    'settings.view': '预览方式',
    'settings.view.states': '按状态',
    'settings.view.actions': '按动作',
    'settings.unusedCount': '{n} 个动作还没有状态在用',
    'settings.showMore': '显示更多',
    'settings.actionFrames': '{n} 帧',
    // ── 编辑器的字段脊柱 ──
    'settings.region.states': '状态',
    'settings.region.action': '动作',
    'settings.region.canvas': '画布',
    'settings.region.frames': '帧（按顺序播放）',
    'settings.region.palette': '画笔',
    'settings.region.library': '动作库',
    'settings.region.preview': '预览',
    'settings.region.frame': '当前帧',
    'settings.field.frames': '帧',
    // ── 动作库 ──
    'settings.libraryHint': '这个裁剪下的全部动作。勾选 = 选中的状态播放它。同一个动作可以勾给多个状态——之后改一次，这几个状态一起变。删除动作在「按动作 · 批量删除」里。',
    'settings.actionHint': '画板上正在编辑的这一个动作。哪些状态播放它，到「按状态」里勾选。',
    'settings.assignCropMissing': '这个裁剪下还没有画布——先到「编辑 · 按动作」生成全身草稿。',
    'settings.builtinStatesOnly': '内置皮肤的像素是固定的；这里能改的是「每个状态播放它的哪些动作」。想自己画就切到「我的创作」。',
    'settings.clearIdleHint': '「空闲」至少要保留一个动作：没有勾选任何动作的状态都跟随它。所以「清空」会留下第一个动作，不会真的清成空的。',
    'settings.editAction': '编辑这个动作',
    'settings.editState': '选择这个状态播放的动作',
    'settings.actionCount': '{n} 个动作',
    'settings.actionN': '动作 {n}',
    'settings.actionName': '名称',
    'settings.actionNameHint': '可选名字，只在这个列表里显示。',
    'settings.newAction': '新建动作',
    'settings.deleteAction': '删除动作',
    'settings.deleteUsed': '删除这个动作——{n} 个状态在用它',
    'settings.importAction': '导入动作',
    'settings.importSearch': '搜索动作…',
    'settings.importHint': '选一个动作，它会覆盖你正在编辑的这一个：名字、帧和节奏都换掉。播放它的状态仍然播放它，撤销可以找回你画的。',
    'settings.importSource.builtin': '内置',
    'settings.importSource.mine': '我的',
    'settings.importCurrent': '当前',
    'settings.importedOne': '已导入「{name}」',
    'settings.usedByN': '{n} 个状态在用',
    'settings.unusedAction': '还没有状态在用',
    'settings.playedHere': '本状态播放它',
    'settings.emptyLibrary': '这个裁剪下还没有动作。',
    // ── 分配列表分两段：先列已勾给该状态的动作，再列其余 ──
    'settings.libraryTickedGroup': '已勾给该状态（{n}）',
    'settings.libraryRestGroup': '其他动作（{n}）',
    'settings.libraryFull': '动作库已满。',
    'settings.selectAll': '全选',
    'settings.clearSelection': '清空',
    // ── finding and bulk-editing actions ──
    'settings.searchActions': '搜索动作…',
    'settings.searchStates': '搜索状态…',
    'settings.searchMatches': '{total} 个动作里匹配 {n} 个',
    'settings.searchEmpty': '没有动作匹配「{q}」。',
    'settings.selectedCount': '已勾选 {n} 个',
    'settings.selectedMax': '已勾选 {n} 个（已到上限）',
    'settings.manageActions': '批量删除',
    'settings.bulkHint': '勾上要删掉的动作，再点「删除选中」——会弹窗确认，因为删除不可撤销。',
    'settings.selectAllHint': '「全选」勾的是搜索匹配的全部动作，不只是当前屏显示的那些。',
    'settings.confirmDeleteTitle': '删除 {n} 个动作？',
    'settings.confirmDeleteHint': '它们会离开动作库，播放它们的状态也会失去这条引用。这一步无法撤销。',
    'settings.cancel': '取消',
    'settings.confirmDelete': '删除',
    'settings.deleteSelected': '删除选中',
    'settings.deleteBlocked': '这个裁剪至少要保留一个动作，而且「空闲」必须保留一个它播放的动作。',
    'settings.actionsRemoved': '已删除 {n} 个动作',
    'settings.followIdle': '跟随空闲',
    'settings.actionMs': '默认每帧',
    'settings.actionMsHint': '一个动作一个节奏：所有播放它的状态都用这个数。',
    'settings.addFrame': '复制一帧',
    'settings.addBlankFrame': '空白帧',
    'settings.emptyBody': '还没有全身像——弹窗里暂时显示头像的 4 倍放大。',
    'settings.blankBody': '从空白网格开始',
    'settings.hint.idle': '平时待命',
    'settings.hint.sleep': '闲置约 1 分钟后',
    'settings.hint.think': '刚发出消息，还没开始回复',
    'settings.hint.stream': '正在输出内容',
    'settings.hint.tool': '正在执行工具',
    'settings.hint.approval': '等待你批准操作',
    'settings.hint.question': '等待你回答问题',
    'settings.hint.error': '上一次执行失败',
    'settings.hint.done': '完成了，你还没看',
    'settings.hint.petted': '被点了一下的瞬间',
    'settings.hint.woken': '睡觉时 hover 或聚焦',
    'settings.export': '导出',
    'settings.import': '导入',
    'settings.io': '导入 / 导出 JSON',
    'settings.importError': '无效的精灵数据',
    'settings.undo': '撤销',
    'settings.redo': '重做',
    'settings.paste': '粘贴',
    'settings.genBody': '从头像生成 128×128 草稿',
    'settings.frameLen': '本帧时长',
    'settings.frameOffset': '整幅挪动',
    'settings.frameOffsetHint': '整幅挪动：不重画笔，只把这一帧整体挪几格——做上下浮动、左右晃动就靠它。',
    'settings.offsetReset': '归零',
    'settings.frameProp': '装饰',
    'settings.framePropClear': '移除装饰',
    'settings.framePropHint': '这一帧带了一个导入的装饰（睡觉气泡、感叹号等），它叠在身体上、不在画板里，所以只能在这里移除。',
    'settings.moveUp': '上移', 'settings.moveDown': '下移',
    'settings.moveLeft': '左移', 'settings.moveRight': '右移',
    'settings.frameN': '第 {n} 帧',
    'settings.framePrev': '这一帧前移', 'settings.frameNext': '这一帧后移',
    'settings.copyFrame': '复制到剪贴板',
    'settings.delFrame': '删除此帧',
    'settings.frameMs': '毫秒/帧',
  },
};

// Only used when the slot supplies no locale translator at all.
export const LABEL_FALLBACK = LABELS.en;

/** The `t` prop type the host hands every slot component. */
export type Translator = ((key: string, params?: Record<string, unknown>) => string) | null | undefined;

/** Resolve a translator prop into a guaranteed callable, with `{param}`
 * interpolation even on the English fallback path. */
export function translatorOrFallback(
  t: Translator,
): (key: string, params?: Record<string, unknown>) => string {
  if (typeof t === 'function') return t;
  return (key, params) => {
    let s = LABEL_FALLBACK[key] || key;
    if (params) {
      for (const name in params) s = s.replace('{' + name + '}', String(params[name]));
    }
    return s;
  };
}
